### ISSUE TITLE
dvs数据集的输入

### ISSUE THREAD

**Issue by wzZero** [ZhejianglabNCRC/SPAIC#11]
自定义了dvscifar10的dataset，主要参照Dataset中的DVS128Gesture，但是这个dataset是不是还没有测试过？

input layer中编码器设置为null(还是应该自定义?)，`__get_item__`返回的spiking返回tensor shape为(10,2,128,128)是不是不行？
结构定义如下
```python
# coding
 self.input = spaic.Encoder(num=node_num, coding_method='null')
 # neuron group
 self.layer1 = spaic.NeuronGroup(128*128, neuron_model='lif')
 self.layer2 = spaic.NeuronGroup(2,neuron_model='lif')
 # decoding
 self.output = spaic.Decoder(num=label_num, dec_target=self.layer2, coding_method='spike_counts')
```
报错`unsupported operand type(s) for +: 'Tensor' and 'NoneType'` 🥲

**Comment by wzZero** [comment]
前向传播第2次`update_step`的时候，发生(100,2,128,128)和(10,16384)进行运算的情况，原来的输入(batch_size,10,2,128,128)在null encoder里前两维进行转置之后成(10,batch_size,2,128,128)，我是应该把(2,128,128)这个拉平吗？

**Comment by wzZero** [comment]
使用(10,128*128)的数据输入，但是在反向传播的时候报错，执行之前设置过zero_grad
`RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn`，

**Comment by isMengxiao** [comment]
> 
输入的时候

> 前向传播第2次`update_step`的时候，发生(100,2,128,128)和(10,16384)进行运算的情况，原来的输入(batch_size,10,2,128,128)在null encoder里前两维进行转置之后成(10,batch_size,2,128,128)，我是应该把(2,128,128)这个拉平吗？

输入的时候是理应转化为（batch_size, time_steps, shape）这种形式的，然后数据的shape要和模型当中的input匹配。。就是如果数据的shape希望是（2,128,128）那么input的shape也需要一样。我看你现在input设置的是2x128x128应该，所以就数据维度会不匹配。

**Comment by isMengxiao** [comment]
zero_grad是模型建立的时候使用有些问题，已经解决了，
